[build-system]
# Can't specify "setuptools-git-versioning>=2.1,<3" until we drop Py3.6 support
requires = ["setuptools>=41", "wheel", "setuptools-git-versioning"]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true
