name: release

permissions:
  contents: write

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*'

jobs:
  build:

    name: Build the module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with tags
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Python module build
        run: |
          rm -rf dist
          python -m build

      - name: Confirm the module version from the .whl file
        id: get-whl-version
        run: |
          pip install pkginfo
          version=$(
            python -c 'from pkginfo import Wheel; import sys; print(Wheel(sys.argv[1]).version)' \
              dist/*-any.whl
          )
          printf '::set-output name=version::%s\n' "$version"

      - name: Create new draft release
        if: github.ref_type == 'tag'
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: dist/*
          fail_on_unmatched_files: true
          make_latest: true

          name: Release ${{ steps.get-whl-version.outputs.version }}
          body: |
            Auto release. See Git log for details.
          prerelease: false
